<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    use HasFactory;

    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
